const submissionsData = {
  title: "Submissions Are Now Open!",
  contentBoxes: [
    {
      logo: require("./circle.png").default,
      title: "Lorem ipsum dolor sit",
      description:
        "Lorem ipsum dolor sit amet, consectet adipiscing elit. Phasellus id erat nec dol interdum pretium sit amet sit amet nib. Pellentesque eget erat nulla pelle.",
    },
    {
      logo: require("./circle.png").default,
      title: "Lorem ipsum dolor sit",
      description:
        "Lorem ipsum dolor sit amet, consectet adipiscing elit. Phasellus id erat nec dol interdum pretium sit amet sit amet nib. Pellentesque eget erat nulla pelle.",
    },
    {
      logo: require("./circle.png").default,
      title: "Lorem ipsum dolor sit",
      description:
        "Lorem ipsum dolor sit amet, consectet adipiscing elit. Phasellus id erat nec dol interdum pretium sit amet sit amet nib. Pellentesque eget erat nulla pelle.",
    },
  ],
  categoriesListing: {
    title: "List of Submission Categories",
    categories: [
      "Action Film",
      "Dark Science Fiction Film",
      "Horror Comedy Film",
      "Dark Drama Screenplay",
      "Action Film",
      "Dark Science Fiction Film",
      "Horror Comedy Film",
      "Dark Drama Screenplay",
      "Action Film",
      "Dark Science Fiction Film",
      "Horror Comedy Film",
      "Dark Drama Screenplay",
      "Action Film",
      "Dark Science Fiction Film",
      "Horror Comedy Film",
      "Dark Drama Screenplay",
      "Action Film",
      "Dark Science Fiction Film",
      "Horror Comedy Film",
      "Dark Drama Screenplay",
      "Action Film",
      "Dark Science Fiction Film",
      "Horror Comedy Film",
      "Dark Drama Screenplay",
      "Action Film",
      "Dark Science Fiction Film",
      "Horror Comedy Film",
      "Dark Drama Screenplay",
      "Action Film",
      "Dark Science Fiction Film",
      "Horror Comedy Film",
      "Dark Drama Screenplay",
      "Action Film",
      "Dark Science Fiction Film",
      "Horror Comedy Film",
      "Dark Drama Screenplay",
      "Action Film",
      "Dark Science Fiction Film",
      "Horror Comedy Film",
      "Dark Drama Screenplay",
    ],
  },
}

export default submissionsData
